/* Modular, replaceable services: image input → diagnosis → weather → timing → advisory. */
const $ = (id) => document.getElementById(id);
const screens = {home: $('homeScreen'), scan: $('scanScreen'), advisory: $('advisoryScreen')};
let photoData = null, chosenLocation = '', demoMode = false;

const scenarios = {
  tomato: { crop:'Tomato', emoji:'🍅', place:'Vijayawada, Andhra Pradesh', disease:'Early Blight', confidence:91, severity:'Moderate', finding:'Brown circular lesions and surrounding yellowing are consistent with early blight symptoms.', actions:['Remove heavily affected leaves and dispose of them away from the field.','Avoid overhead watering; keep leaves as dry as possible.','Follow locally recommended treatment guidance for early blight.','Check nearby plants every day for new spots.'], weather:{temp:29, humidity:78, rain:70, wind:11, summary:'Rain is expected later today.'} },
  rice: { crop:'Rice', emoji:'🌾', place:'Guntur, Andhra Pradesh', disease:'Leaf Blast', confidence:88, severity:'Moderate', finding:'Diamond-shaped lesions with grey centres are consistent with rice leaf blast.', actions:['Remove or isolate severely affected plants where practical.','Avoid excess nitrogen application until the field is reviewed.','Use only locally recommended disease-management treatment.','Monitor surrounding rows for fresh lesions.'], weather:{temp:27, humidity:62, rain:10, wind:7, summary:'Dry conditions are expected through tomorrow morning.'} },
  cotton: { crop:'Cotton', emoji:'☘', place:'Warangal, Telangana', disease:'Leaf Spot', confidence:84, severity:'Low to Moderate', finding:'Small dark spots and leaf yellowing are consistent with a leaf spot problem.', actions:['Remove leaves that are heavily affected.','Improve air movement between plants where possible.','Avoid wetting leaves during irrigation.','Consult local guidance if spots spread quickly.'], weather:{temp:30, humidity:91, rain:35, wind:9, summary:'Very high humidity may encourage fungal disease spread.'} }
};
const diagnosisKnowledge = {
  Tomato: scenarios.tomato, Rice: scenarios.rice, Cotton: scenarios.cotton,
  Chilli: { ...scenarios.tomato, crop:'Chilli', emoji:'🌶️', disease:'Leaf Spot', confidence:76, finding:'Visible spotting and yellowing suggest a leaf spot problem. A closer image can improve confidence.' },
  Maize: { ...scenarios.cotton, crop:'Maize', emoji:'🌽', disease:'Leaf Blight', confidence:74, finding:'Leaf lesions and discoloration may indicate leaf blight. Consider expert verification.' },
  Potato: { ...scenarios.tomato, crop:'Potato', emoji:'🥔', disease:'Early Blight', confidence:79 },
  Groundnut: { ...scenarios.cotton, crop:'Groundnut', emoji:'🥜', disease:'Leaf Spot', confidence:77 }
};
const ImageInput = { async validate(file){ if(!file) return {ok:false, message:'Add a clear photo of one affected leaf first.'}; if(file.size < 5000) return {ok:false,message:'We need a clearer crop image. Try one affected leaf in good lighting.'}; return {ok:true}; } };
const DiseaseDiagnosis = { diagnose(crop){ return diagnosisKnowledge[crop] || {...scenarios.cotton,crop:crop||'Crop',emoji:'🌱',disease:'Leaf damage detected',confidence:62,severity:'Needs review',finding:'We can see leaf damage, but a closer, well-lit image and expert review will help identify the cause.'}; } };
const WeatherService = { async get(place, fallback){
  try { const query = encodeURIComponent(place); const geo = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${query}&count=1`).then(r=>r.json()); const loc=geo.results?.[0]; if(!loc) throw Error(); const data=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${loc.latitude}&longitude=${loc.longitude}&current=temperature_2m,relative_humidity_2m,wind_speed_10m&hourly=precipitation_probability&forecast_days=2`).then(r=>r.json()); return { temp:Math.round(data.current.temperature_2m),humidity:data.current.relative_humidity_2m,wind:Math.round(data.current.wind_speed_10m),rain:Math.max(...data.hourly.precipitation_probability.slice(0,12)),summary:`Live conditions for ${loc.name}, ${loc.admin1 || ''}`.replace(/, $/,''),place:`${loc.name}${loc.admin1 ? ', '+loc.admin1 : ''}`}; } catch { return {...fallback, place}; }
} };
const ActionTimingEngine = { decide(weather){ const rain = weather.rain >= 45, wind = weather.wind >= 18, humid = weather.humidity >= 85; if(rain) return {window:'Tomorrow · 6:30–9:30 AM',reason:'Drier conditions and gentler wind make this a safer treatment window.',title:'Avoid spraying tonight',warning:'Expected rainfall could wash off treatment and increase fungal spread.'}; if(wind) return {window:'Tomorrow · Early morning',reason:'Wind is expected to be lower, helping treatment stay on the target plants.',title:'Avoid spraying in strong wind',warning:'Wind can carry spray off-target. Wait for a calmer period.'}; if(humid) return {window:'Tomorrow · 7:00–9:00 AM',reason:'Morning conditions should be calmer; avoid unnecessary leaf wetness.',title:'Disease risk increasing',warning:'High humidity can encourage fungal spread. Improve air flow and keep foliage dry.'}; return {window:'Today · 6:30–9:30 AM',reason:'Low rain chance and moderate wind make this a suitable treatment window.',title:'Avoid treating during rain',warning:'Conditions can change quickly—do not treat if rainfall begins.'}; } };

function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function selectedScenario(){return scenarios.tomato;}
function render(advisory){ const {d,weather,timing}=advisory; $('resultEmoji').textContent=d.emoji;$('diseaseName').textContent=d.disease;$('severity').textContent=d.severity;$('confidenceText').textContent=`${d.confidence}% confidence`;$('confidenceLabel').textContent=d.confidence>=85?'HIGH CONFIDENCE':d.confidence>=70?'MODERATE CONFIDENCE · CONSIDER EXPERT VERIFICATION':'LOW CONFIDENCE · EXPERT REVIEW ADVISED';$('confidenceBar').style.width=`${d.confidence}%`;$('findingText').textContent=d.finding;$('actionsList').innerHTML=d.actions.map(a=>`<li>${a}</li>`).join('');$('weatherLocation').textContent=weather.place||d.place;$('temperature').textContent=`${weather.temp}°`;$('humidity').textContent=`${weather.humidity}%`;$('rainChance').textContent=`${weather.rain}%`;$('windSpeed').textContent=weather.wind;$('weatherSummary').textContent=weather.summary;$('weatherIcon').textContent=weather.rain>=45?'🌧️':weather.humidity>=85?'💧':'🌤️';$('bestWindow').textContent=timing.window;$('timingReason').textContent=timing.reason;$('warningTitle').textContent=timing.title;$('warningText').textContent=timing.warning; localStorage.setItem('cropDoctorRecent',JSON.stringify({disease:d.disease,place:weather.place||d.place})); show('advisory'); }
async function analyze(forced){ const crop=forced?.crop || $('cropSelect').value; const location=forced?.place || chosenLocation || $('manualLocation').value.trim(); if(!forced){const result=await ImageInput.validate($('photoInput').files[0]);if(!result.ok){$('formMessage').textContent=result.message;return;}if(!crop){$('formMessage').textContent='Choose the crop so we can give better guidance.';return;}if(!location){$('formMessage').textContent='Use your location or enter a town or village.';return;}} $('loading').classList.remove('hidden');const d=forced || DiseaseDiagnosis.diagnose(crop); const weather= demoMode ? {...d.weather,place:location||d.place} : await WeatherService.get(location||d.place,d.weather); const timing=ActionTimingEngine.decide(weather); setTimeout(()=>{ $('loading').classList.add('hidden');render({d,weather,timing});},700); }
$('startScan').onclick=()=>show('scan');$('homeButton').onclick=()=>show('home');document.querySelectorAll('[data-home]').forEach(x=>x.onclick=()=>show('home'));document.querySelectorAll('[data-scan]').forEach(x=>x.onclick=()=>show('scan'));
$('photoInput').onchange=async(e)=>{const file=e.target.files[0];if(!file)return;const valid=await ImageInput.validate(file);if(!valid.ok){$('formMessage').textContent=valid.message;return;}photoData=URL.createObjectURL(file);$('imagePreview').src=photoData;$('previewWrap').classList.remove('hidden');$('uploadZone').classList.add('hidden');$('formMessage').textContent='';};$('removePhoto').onclick=()=>{$('photoInput').value='';$('previewWrap').classList.add('hidden');$('uploadZone').classList.remove('hidden');};
$('locationButton').onclick=()=>{if(!navigator.geolocation){$('formMessage').textContent='Location is unavailable—enter your town or village.';return;}$('locationLabel').textContent='Finding your field…';navigator.geolocation.getCurrentPosition(pos=>{chosenLocation='Your current field';$('locationLabel').textContent='📍 Your current field';$('homeLocation').textContent='📍 Your current field';},()=>{$('locationLabel').textContent='Use current location';$('formMessage').textContent='We could not access your location. Please enter it manually.';},{timeout:7000});};
$('diagnoseButton').onclick=()=>analyze();document.querySelectorAll('.scenario').forEach(b=>b.onclick=()=>{demoMode=true;$('demoToggle').classList.add('on');analyze(scenarios[b.dataset.scenario]);});$('demoToggle').onclick=()=>{demoMode=!demoMode;$('demoToggle').classList.toggle('on',demoMode);};
const recent=JSON.parse(localStorage.getItem('cropDoctorRecent')||'null');if(recent){$('recentCard').innerHTML=`<div class="section-label">MOST RECENT ADVISORY</div><div style="margin-top:12px;font-size:18px;font-weight:800">🌱 ${recent.disease}</div><p style="color:#6e7d73;font-size:13px;margin:5px 0 0">${recent.place} · Tap Scan your crop for a new field check.</p>`;}
